### ISSUE TITLE
Different performance between RNN and CNN

### ISSUE THREAD

**Issue by IceFlowerLi** [ROCm/MIOpen#128]
When I run the classical  model Seq2seq in my machine with this [program,](https://github.com/keon/seq2seq) I found that the program consits of RNN structures with the same parameters is far slower than NVIDIA platform even the Float32 performance of the Radeon 7 is greater than 1080ti. But the perfromance is proved in CNN operations that the Radeon 7 is faster than 1080ti in official pytorch examples [mnist.](https://github.com/pytorch/examples/tree/master/mnist) Here is the comparation table:

||Radeon 7|1080ti|
|---|---|---|
|Concurrency platform|ROCm 2.9|CUDA 10.0|
|Deep learning software|MIOpen 2.1|cuDNN 7.5|
|Pytorch|1.3.1|1.3.1|
|Seq2seq time|19min|10min|
|Mnist time|2min39s|3min59s|

I also try myself experiments that consist more complex RNN structure and large datasets. The program costs **2** hours per epoch in 1080ti and **9** hours per epoch in Radeon 7 with the same parameters. Of course, I am happy to see that others can give more test in more complex RNN and CNN models.
In nvidia cuDNN official [website](https://developer.nvidia.com/cudnn), we can see the performance in sequence model achieve a large increment between the different version of cuDNN. Should our MIOpen library need more optimization in RNN operation?

**Comment by qixiang109** [comment]
I also find the same problem. Compared with a GTX1080, my radeon vii is about 1.7x faster in most CNN nets, a litter slower in RNN nets, and much slower in Depthwise-Separable Conv (e.g., mobilenet) , about 1/7 the speed of GTX1080.

As with RNN nets, simply increasing batch size makes radeon vii faster. I guess either the gpu frequency is the bottleneck since RNNs are not very parallelizabl, or the miopen lib is not  so optimized for rnns.

below is the performance on a 2 layer bilstm
|  batch size  | Radeon Vii  | GTX1080 |
|  ----  | ----  |----  |
| 64  | 120 | 191 |
| 128  | 206  | 291 |
| 256  | 318 | 318 |
| 512  |  448 | OOM |

**Comment by ppanchad-amd** [comment]
Apologies for the lack of response. Please try latest ROCm 6.0.2 to see if your issue has been resolved? If resolved, please close the ticket. Thanks.
