### ISSUE TITLE
ROCm5.5 build fails during cmake stage: missing file: gfx90a6e.kdb.bz2

### ISSUE THREAD

**Issue by jdgh000** [ROCm/MIOpen#2255]
-- Build with HIPRTC
-- Found Boost: /usr/local/lib/cmake/Boost-1.79.0/BoostConfig.cmake (found version "1.79.0") found components: filesystem
-- HALF_INCLUDE_DIR: /opt/rocm/include
CMake Error at CMakeLists.txt:509 (file):
  file failed to open for reading (No such file or directory):

    /home/u1/ROCm-5.5/MIOpen/src/kernels/gfx90a68.kdb.bz2
Call Stack (most recent call first):
  CMakeLists.txt:534 (install_kdb)

CMake Error at CMakeLists.txt:509 (file):
  file failed to open for reading (No such file or directory):

    /home/u1/ROCm-5.5/MIOpen/src/kernels/gfx90a6e.kdb.bz2
Call Stack (most recent call first):
  CMakeLists.txt:534 (install_kdb)

**Comment by junliume** [comment]
Hi @jdgh000 this file is hosted via `git-lfs`. Did you check the size of the file on your local system? If not pulled via LFS, the size would be like 143 ;-P

**Comment by jdgh000** [comment]
I dont understand your comment. What do you mean the check the file on your system? What size do I expect? Where in the build instruction has steps for checking the file on the system such that build will be successful?? I dont see anywhere: https://github.com/ROCmSoftwarePlatform/MIOpen.
Sure, there is a section about git-lfs informational stuff but it is unclear how it is related to build.

**Comment by junliume** [comment]
Hi @jdgh000 sorry for the delayed response. Could you please check:
> ~/MIOpen$ ls -ltrah src/kernels/gfx90a6e.kdb.bz2
> -rw-rw-r-- 1 amd amd 259M Jul  6 19:36 src/kernels/gfx90a6e.kdb.bz2

We expect the size of `src/kernels/gfx90a6e.kdb.bz2` to be several hundreds of Ms instead of zero (or 143 as it may show up in the above command).

Let me explain a bit what is going on here:

-  First of all, we acknowledge MIOpen should have an improved documentation, more user focused and more user friendly. We are working on it, and better yet, we would greatly appreciate input from our users so that we can improve it! If you could summarize a few issues you have met by following our documentations of installation, please let us know and I will surely have it assigned and fixed asap.
- The file `src/kernels/gfx90a6e.kdb.bz2` is a kernel cache for better out-of-box performance so that any user does not have the need to compiler these kernels when they first met them. However, naturally these files will be very large (larger than what GitHub recommends for GIT-LFS version control) and they are binaries.
- For the above reason, MIOpen is using GIT-LFS for these binary files.
- However, understandably, `git lfs` sometimes are not installed already on user system, so when you cloned MIOpen repo, these files are not downloaded automatically and shows up as zero sizes instead (e.g. https://stackoverflow.com/questions/65363299/git-clone-lfs-files-not-fully-downloading)
- A recommended solution is to install Git LFS: `git lfs install`

Could you please check if the above info is helpful? Thanks!
