### ISSUE TITLE
Is  there  a way to speed up build? 1) specify gpu target 2) point to prebuild CK library?

### ISSUE THREAD

**Issue by jdgh000** [ROCm/MIOpen#3396]
1) is it possible to implemented GPU_TARGET as in some of other ROCm stack?
2) Currently MIOpen build takes very long ~1.5hr, it seems CK is being built during MIOpen build (based on partial log below). There seems MIOPEN_USE_COMPOSABLEKERNEL parameter in CMakeLists.txt to control using CK. However is there a way to still use CK but re-use prebuilt CK library?
Just like how in rocBLAS, build time can be greatly reduced up by using -t <tensile_path> in which if Tensile is prebuilt already. 

```
-- Build files have been written to: /usr/local/cget/build/tmp-22f234757dc847fabd5c35e48512f50a/build
[  0%] Building CXX object library/src/tensor_operation_instance/gpu/transpose/CMakeFiles/device_transpose_instance.dir/device_transpose_instances_3d.c>
[  2%] Building CXX object library/src/tensor_operation_instance/gpu/column_to_image/CMakeFiles/device_column_to_image_instance.dir/device_column_to_im

find .. -name tensor_operation_instance
../composable_kernel/library/include/ck/library/tensor_operation_instance
../composable_kernel/library/src/tensor_operation_instance
../composable_kernel/build/library/src/tensor_operation_instance


```

**Comment by ppanchad-amd** [comment]
Hi @jdgh000. Internal ticket has been created to assist with your issue. Thanks!

**Comment by tcgu-amd** [comment]
Hi @jdgh000, unfortunately the latest MIOpen versions depends on specific commits of CK that needs to be built separately. The easiest way I recommend to speed up the process is using prebuilt MIOpen docker images from here https://hub.docker.com/r/rocm/miopen/tags. Thanks!

**Comment by tcgu-amd** [comment]
> i am not seeing response for #1. -a for setting gfx, as in other ROCm components. For #2, i am not quite understanding the response. What do you mean by "speed up process"? I am not needing prebuilt miopen, issue I asked here is build speed itself.

Hi @jdgh000 , sorry for the confusion. I will clarify my answer:

Regarding #1, I don't think there is such an option for MI Open itself, but if you are asking for it's dependency, you might be able to achieve this by modifying line 10 of requirement.txt to 

```
ROCm/composable_kernel@c5ad2e8075ccaf3457a41884b25f3dbe85bf251c -DCMAKE_BUILD_TYPE=Release -DGPU_TARGETS="gfx<number>"
```

For #2, unfortunately that's not really possible. Even if one were to find a way to hook the existing CK, it's like going to cause errors since MIOpen depends on specific versions of CK that needs to build separately from existing CK installed on your system. 

If building speed is a concern, you can build MIOpen in one of the pre-built docker images (i.e. the docker has all the dependencies, including the specific version of CK already compiled). So all you need is pulling the docker image from the docker hub, which should be faster depending on your internet connection. 

Hopefully this answers your question.

Thanks!

**Comment by jdgh000** [comment]
You are not getting full picture for #2, I cited example for rocblas with tensile which also keeps tag of tensile commit. The stuff you are descriving impossible is exactlly what is already done for Rocblas/tensile which it keeps in tensile_tag file. I suggest to look and compare before jumping to conclusion.

**Comment by tcgu-amd** [comment]
@jdgh000, Hi, thanks for the additional info. Sorry, I assumed [this](https://github.com/ROCm/rocBLAS/blob/e5e610b6ba9f1d968259c0e37de68835025a8327/CMakeLists.txt#L192) is what you were referring to, in which case no MIOpen does not provide similar functionality, and it is not possible to achieve it with the current MIOpen build configuration. This is because MIOpen **requires specific versions of CK**, else **it will not work**. Therefore it wouldn't really make sense to implement a functionality that allows linking custom pre-built CK. To you are building MIOpen multiple times and wants to avoid building CK after the first, you can delete CK's line from requirements.txt. Else, if you simply have **some** version of CK prebuilt, it is likely not going to work with MIOpen and you would want to build the custom CK from MIOpen again. The way this works is likely not going to change unfortunately.

**Comment by tcgu-amd** [comment]
Hi, I will be closing this issue for now due to inactivity. Please feel free to reopen and/or add follow up questions. Thanks!
