### ISSUE TITLE
[NHWC] gemm algorithm not support NHWC

### ISSUE THREAD

**Issue by carlushuang** [ROCm/MIOpen#742]
As addressed in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/728, gemm solver will not get correct result when using NHWC layout `--in_layout NHWC --out_layout NHWC --fil_layout NHWC`. We may need disable gemm with NHWC, or fix it.

cc @jerryyin @asroy @atamazov @zjing14

**Comment by jerryyin** [comment]
Strictly speaking there are two elements to this issue:

In the short term (before June), we want to just disable gemm such that NHWC config won't accidentally fallback to NCHW gemm.

In the long term (after June), gemm should be able to execute on NHWC format.

**Comment by ce1adon** [comment]
Do we know who owns this issue?

**Comment by ce1adon** [comment]
What is the priority?

**Comment by jerryyin** [comment]
@JehandadKhan FYI, since this is a work item in the NHWC prototyping issue. We need to decide on a short term goal owner to this one.

I believe from my past conversation with @daniellowell, the long term goal will be assigned to either @ce1adon or @zjing14. Not sure if you guys have any impressions on this.

**Comment by ce1adon** [comment]
@jerryyin Yes I implemented part of the gemm path. I can take a look and evaluate what need to be done.

**Comment by JehandadKhan** [comment]
Do we really need a fallback to rocBlas? If we have @carlushuang's kernel ? 

@asroy and @zjing14 can you comment ? AFAIU the plan was to fallback on the GPU golden kernel and not do

**Comment by jerryyin** [comment]
@JehandadKhan I will try to answer your question to the best knowledge I have, but at the end of the day, it is probably still up to MIOpen team to decide.

> Do we really need a fallback to rocBlas? If we have @carlushuang's kernel ?

My understanding is that @carlushuang's kernel is only as good as a backup for June's delivery, but does not meet the performance as a justified production kernel (10x slower than gemm). This way, in the long term, work related to gemm fallback is still needed. I could be wrong tho. My impression had been that @carlushuang's kernel and gemm fallback path are always independent things.

In the short term, I'm more worried about whether gemm fallback path get properly handled (since it is not disabled now). If MIOpen requested memory according to the wrong gemm fallback, it can easily use up all memory for running resnet50.

**Comment by JehandadKhan** [comment]
Thanks @jerryyin that makes sense. I believe at the very least we need to make sure if the rocblas fallback is exercised it provides correct result as well as the correct size for the workspace. I will let @ce1adon scope the work out and formulate a plan given her work engagements.

**Comment by ce1adon** [comment]
@jerryyin 
I talked to @daniellowell about my duty this year and learnt that this topic is currently assigned to me. Working on a plan. Feel free to reach me offline directly any time.

**Comment by atamazov** [comment]
@jerryyin 
> In the short term, I'm more worried about whether gemm fallback path get properly handled (since it is not disabled now). 

+1 Lets quickly disable Gemm, #744 created.

**Comment by jerryyin** [comment]
@atamazov Thanks, I just had a meeting with @ce1adon and @asroy. I'd fine with proceeding with `MIOPEN_DEBUG_CONV_GEMM=0` provided that it gives correct result. @ce1adon agreed to examine specifically the workspace now.

**Comment by ce1adon** [comment]
See comments here https://github.com/ROCmSoftwarePlatform/MIOpen/issues/744#issuecomment-780162112
